name: Tests

on:
  pull_request:
    paths:
      - 'custom_components/**'
      - 'tests_enphase_cloud_things/**'
      - 'pyproject.toml'
      - '.ruff.toml'
      - '.github/workflows/tests.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.13' ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            pyproject.toml
            .github/workflows/tests.yml
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -U pytest pytest-asyncio pytest-homeassistant-custom-component homeassistant aiohttp async-timeout voluptuous
      - name: Run tests
        run: pytest -q
